version: "3.3"

services:      
  catalog:
    build: cmd/catalog
    depends_on:
      - gotway
    environment:
      - CATALOG_SERVICE_PORT=9000
    ports:
      - "9000:9000"

  stock:
    build: cmd/stock
    depends_on:
      - gotway
      - redis
    environment:
      - STOCK_SERVICE_PORT=10000
      - REDIS_URL=redis:6379
    ports:
      - "10000:10000"

  route:
    build: cmd/route
    depends_on:
      - gotway
    environment:
      - ROUTE_SERVICE_PORT=11000
    ports:
      - "11000:11000"
