version: "3.3"

services:      
  catalog:
    image: gotwaygateway/catalog:v0.0.1
    environment:
      - CATALOG_SERVICE_PORT=12000
    ports:
      - "12000:12000"

  stock:
    image: gotwaygateway/stock:v0.0.1
    depends_on:
      - redis
    environment:
      - STOCK_SERVICE_PORT=10000
      - REDIS_URL=redis:6379
    ports:
      - "13000:13000"

  route:
    image: gotwaygateway/route:v0.0.1
    environment:
      - ROUTE_SERVICE_PORT=14000
    ports:
      - "14000:14000"
