version: "3.3"

services:
  redis:
    container_name: gotway-redis
    image: redis:6.2.4-alpine3.13
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data

  catalog:
    container_name: gotway-catalog
    image: gotwaygateway/catalog:v0.0.1
    environment:
      - CATALOG_SERVICE_PORT=12000
    ports:
      - "12000:12000"

  stock:
    container_name: gotway-stock
    image: gotwaygateway/stock:v0.0.1
    depends_on:
      - redis
    environment:
      - STOCK_SERVICE_PORT=10000
      - REDIS_URL=redis:6379
    ports:
      - "13000:13000"

  route:
    container_name: gotway-route
    image: gotwaygateway/route:v0.0.1
    environment:
      - ROUTE_SERVICE_PORT=14000
    ports:
      - "14000:14000"
